[package]
name = "blockcipher"
version = "0.1.0"
authors = ["Dan Fockler <dfockler13@gmail.com>"]

[dependencies]
generic-array = "0.9.0"
block-cipher-trait = { git = "https://github.com/RustCrypto/traits" }
